name: Daily Build

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/_release.yml
    with:
      enable_scoop: true
      enable_winget: true
      tag_strategy: overwrite
    secrets: inherit
